кек
inik01/Ucheba pull request #2
Opened 2022-02-24 15:38 UTC by inik01

2022-02-24 21:00 UTC, dmitrii-kruglov requested changes

2022-02-24 21:00 UTC, dmitrii-kruglov commented on конь
> +/конь
И что же сделано?

2022-02-25 18:32 UTC, inik01 commented on конь
> +/конь
Написан код на C#

2022-02-25 18:34 UTC, merged

2022-02-25 19:24 UTC, dmitrii-kruglov requested changes
Выглядит замечательно, а почему не на с++? В чем сложность?

2022-02-25 19:24 UTC, dmitrii-kruglov commented on конь
> +        static void Main(string[] args)
А что не через классы?)

2022-02-25 19:24 UTC, dmitrii-kruglov commented on конь
> +            int xk, yk, xp, yp, xf, yf;
Вот чтобы такого не было, хорошо было бы использовать классы, хотя бы для хранения координат фигур

2022-02-25 19:24 UTC, dmitrii-kruglov commented on конь
> +            if (xp <= 0 || xp >= 8 || yp <= 0 || yp >= 8) // пешка за полем или на неположеном месте?
вот это тоже можно вытащить в функцию класса фигура...

2022-02-25 19:25 UTC, dmitrii-kruglov commented
И на лекции, и на семинаре говорим о нечитаемости большого кол-ва строк в коде) Было бы замечательно разбить этот код хотя бы на функции